alerta-covid/config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }
  namespace :api do
    namespace :v1 do
      resources :areas, only: [:index]
      resources :covid_tests, only: [:index]
      resources :departaments, only: [:index]
      resources :incidences, only: [:index, :create, :update]
      resources :institutions, only: [:index]
      resources :places, only: [:index]
      resources :symptoms, only: [:index]   
      
      # User confirmation by API
      get 'confirm_user', to: 'confirmations#confirm_user'
      # User Edition by API
      patch :user, to: 'users#update'
      patch 'user_update_password', to: 'users#update_password'
      #User login by API
      post 'login', to: 'sessions#create'
      get '/auto_login', to: 'sessions#auto_login'

      get 'reports/places'
      get 'reports/users'
    end
  end
  
  resources :areas
  resources :covid_tests
  resources :departaments
  resources :incidences
  resources :institutions
  resources :places
  resources :roles
  resources :symptoms  
  
  scope :admin do
    resources :users
  end
  
  root 'home#home'
  get 'home/home'
  get 'home/comfirmation'
  get 'reports/places'
  get 'reports/users'
  # Ex:- scope :active, -> {where(:active => true)}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alerta-covid/app/models/role.rb
class Role < ApplicationRecord
    validates :name, presence: true
    has_many :users
    has_and_belongs_to_many :permissions
    after_destroy :delete_permissions_role

    def set_permissions(permissions)
        permissions.each do |id|
            permission = Permission.find(id)
            self.permissions << permission
        end
    end

    def delete_permissions_role
      ActiveRecord::Base.connection.execute("DELETE FROM permissions_roles WHERE role_id = #{self.id.to_s}")
    end
end

alerta-covid/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  before_action :is_super_admin?
  before_action :set_role, only: %i[show edit update destroy]

  load_and_authorize_resource
  before_action :load_permissions

  def index
    #you dont want to set the permissions for Super Admin.
    @roles = Role.all.where.not(name: "Super Admin").paginate(page: params[:page], per_page: 10)
  end

  def show
    @permissions = @role.permissions
  end

  def new
    @permissions = Permission.all.map{ |i| i if (["all"].exclude? i.subject_class) }.compact
    @role = Role.new
  end

  def edit
    #we dont want the Drawing permissions to be displayed.
    #this way u can display only selected models. you can choose which methods u want to display too.
    @permissions = Permission.all.map{|i| i if (["all"].exclude? i.subject_class) }.compact
    @role_permissions = @role.permissions.collect{|p| p.id}
  end

  def create
    @role = Role.new(role_params)
    @role.permissions = []
    @role.set_permissions(params[:permissions]) if params[:permissions]
    @permissions = Permission.all.map{ |i| i if (["all"].exclude? i.subject_class) }.compact
    if @role.save
      redirect_to @role, notice: "Role was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @role.permissions = []
    @role.set_permissions(params[:permissions]) if params[:permissions]
    if @role.save
      redirect_to roles_path and return
    end
    @permissions = Permission.all.map{|i| i if (["all"].exclude? i.subject_class) }.compact
    render 'edit'
  end

  def destroy
    if(@role.users.count == 0)
      @role.destroy
      redirect_to roles_url, notice: "Role was successfully destroyed."
    else
      redirect_to roles_url, alert: "Role is being using by users."
    end
  end

  private

  def is_super_admin?
    redirect_to root_path and return unless current_user.super_admin?
  end

  def role_params
    params.require(:role).permit(:name)
  end

  def set_role
    @role = Role.find(params[:id])
  end
end

alerta-covid/app/helpers/roles_helper.rb
module RolesHelper
end

alerta-covid/app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation" class="errors">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :name, class: role.errors.include?(:name) ? "form-control is-invalid" : "form-control" %>
    </div>
  </div>

  <br>

  
  <div class="field">
    <%= form.label :permissions %>
    <div class='table-responsive mt-4'>
      <table class='table table-hover'>
        <thead>
            <tr>
              <th>Class</th>
              <th>Action</th>
              <th><%= check_box_tag('main', 0, false) %></th>
            </tr>
        </thead>

        <tbody>
            <% @permissions.each do |permission| %>
              <tr>
                  <td><%= permission.subject_class %></td>
                  <td><%= permission.action %></td>
                  <td><%= check_box_tag 'permissions[]', permission.id, false, { array: true, class: "check_box" } %></td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="d-flex">
    <%= form.submit class: "btn btn-info w-100" %>
  </div>
<% end %>

alerta-covid/app/views/roles/edit.html.erb
<div class='container'>
  <%= form_with(model: @role) do |form| %>
    <h1 class="title"><%= @role.name %></h1>
    <h6 class="mt-2">Permissions</h6>

    <div class='table-responsive mt-4'>
      <table class='table table-hover'>
        <thead>
          <tr>
						<th>Class</th>
						<th>Action</th>
						<th><%= check_box_tag('main', 0, false) %></th>
          </tr>
        </thead>
				<tbody>
          <% @permissions.each do |permission| %>
            <tr>
							<td><%= permission.subject_class %></td>
							<td><%= permission.action %></td>
							<td><%= check_box_tag 'permissions[]', permission.id, @role_permissions.include?(permission.id), {array: true, class: "check_box"} %></td>
          	</tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="actions mb-3">
      <%= form.submit "Update Role", class: 'btn btn-info w-100' %>
    </div>
  <% end %>
</div>
<div class="container">
  <%= link_to roles_path, { class: "btn return-button mt-5 mb-5"} do %>
    <i class="fas fa-arrow-circle-left"></i>
    Back
  <% end %>
</div>

alerta-covid/app/views/roles/index.html.erb
<div class='container container-form'>

  <h1 class="title mt-2">Super Admin: Listing Roles</h1>

  <div class='table-responsive mt-4'>
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @roles.each do |role| %>
          <tr>
            <td><%= role.name %></td>
            <td>
              <a href="<%= edit_role_path(role) %>" class="btn btn-info">Edit</a>
            </td>
            <td>
              <a href="<%= role_path(role) %>" class="btn btn-warning">Show</a>
            </td>
            <td>
              <%= button_to 'Destroy', role, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="mt-2 col-xs-12">
    <%= will_paginate(@roles, :renderer => WillPaginate::ActionView::LinkRenderer, class: 'pagination-sm justify-content-center') %>
  </div>

  <div class="mt-2 col-xs-12">
    <%= link_to 'New Role', new_role_path, class: 'new-button' %>
  </div>
</div>

alerta-covid/app/views/roles/new.html.erb
<div class="container">
  <h1 class="title">New Role</h1>
  <%= render 'form', role: @role %>
</div>
<div class="container">
  <%= link_to roles_path, { class: "btn return-button mt-5 mb-5"} do %>
    <i class="fas fa-arrow-circle-left"></i>
    Back
  <% end %>
</div>

alerta-covid/app/views/roles/show.html.erb
<div class='container container-form'>

  <h1 class="mt-2 title"><%= @role.name %></h1>

  <div class='table-responsive mt-4'>
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Class</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @permissions.each do |permission| %>
            <tr>
                <td><%= permission.subject_class %></td>
                <td><%= permission.action%></td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>