alerta-covid/config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }
  namespace :api do
    namespace :v1 do
      resources :areas, only: [:index]
      resources :covid_tests, only: [:index]
      resources :departaments, only: [:index]
      resources :incidences, only: [:index, :create, :update]
      resources :institutions, only: [:index]
      resources :places, only: [:index]
      resources :symptoms, only: [:index]   
      
      # User confirmation by API
      get 'confirm_user', to: 'confirmations#confirm_user'
      # User Edition by API
      patch :user, to: 'users#update'
      patch 'user_update_password', to: 'users#update_password'
      #User login by API
      post 'login', to: 'sessions#create'
      get '/auto_login', to: 'sessions#auto_login'

      get 'reports/places'
      get 'reports/users'
    end
  end
  
  resources :areas
  resources :covid_tests
  resources :departaments
  resources :incidences
  resources :institutions
  resources :places
  resources :roles
  resources :symptoms  
  
  scope :admin do
    resources :users
  end
  
  root 'home#home'
  get 'home/home'
  get 'home/comfirmation'
  get 'reports/places'
  get 'reports/users'
  # Ex:- scope :active, -> {where(:active => true)}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alerta-covid/app/models/incidence.rb
class Incidence < ApplicationRecord
  validates :user_id, presence: true
  validates :covid_test_id, presence: true
  validates :open, presence: true
  validates :begin, presence: true

  belongs_to :user
  belongs_to :covid_test
  has_many :incidence_symptoms
  has_many :symptoms, through: :incidence_symptoms
  has_many :incidence_places
  has_many :places, through: :incidence_places

  before_update :set_close

  def set_symptoms(symptoms)
    self.symptoms = []
    symptoms.each do |id|
      symp = Symptom.find(id)
      self.symptoms << symp
    end
  end

  def set_places(places)
    self.places = []
    places.each do |id|
      place = Place.find(id)
      self.places << place
    end
  end

  def set_close
    self.close = DateTime.now if close.nil? && !delivery.nil?
  end

  def has_symptoms
    self.symptoms.count > 0 ? "Yes" : "No"
  end

  def has_symptoms?
    self.symptoms.count > 0
  end
end

alerta-covid/app/controllers/api/v1/incidences_controller.rb
class Api::V1::IncidencesController < Api::V1::ApiController
  def index
    @incidences = Incidence.all
    render json: @incidences, status: :ok
  end

  def create
    @incidence = Incidence.new(incidence_params)
    @incidence.open = DateTime.now()
    set_variables_with_params()
    if @incidence.save
      render json: @incidence, status: :created
    else
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end

  def update
    set_variables_with_params()
    if @incidence.update(incidence_params_update)
      render json: @incidence, status: :ok
    else
      rrender json: { error: e.message }, status: :unprocessable_entity
    end
  end

  private

  def incidence_params
    params.require(:incidence).permit(:covid_test_id, :user_id, :begin)
  end

  def incidence_params_update
    params.require(:incidence).permit(:delivery, :result)
  end

  def set_variables_with_params
    @incidence.set_symptoms(params[:symp]) if params[:symp]
    @incidence.set_places(params[:places]) if params[:places]
  end
end

alerta-covid/app/controllers/incidences_controller.rb
class IncidencesController < ApplicationController
  before_action :set_incidence, only: %i[show edit update destroy]
  before_action :set_variables, only: %i[new edit create update]
  before_action :set_user_symptoms, only: %i[new edit create update]

  # GET /incidences or /incidences.json
  def index
    if(current_user.super_admin?)
      @incidences = Incidence.all.paginate(page: params[:page], per_page: 15)
    elsif(current_user.admin_institution?)
      @incidences = Incidence.joins(user: [:departament]).where("institution_id = #{current_institution.id}").paginate(page: params[:page], per_page: 15)
    else
      @user = current_user
      @incidences = @user.incidence.paginate(page: params[:page], per_page: 15)
    end
  end

  # GET /incidences/1 or /incidences/1.json
  def show; end

  # GET /incidences/new
  def new
    @incidence = Incidence.new
  end

  # GET /incidences/1/edit
  def edit
    @user_symptoms = @incidence.symptoms.collect { |p| p.id }
    @user_places = @incidence.places.collect{ |p| p.id }
    @current_institution = current_institution
  end

  # POST /incidences or /incidences.json
  def create
    @incidence = Incidence.new(incidence_params)
    @incidence.user = current_user
    @incidence.open = DateTime.now()
    set_variables_with_params()
    if @incidence.save
      redirect_to @incidence, notice: 'Incidence was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /incidences/1 or /incidences/1.json
  def update
    set_variables_with_params()
    
    if @incidence.update(incidence_params_update)
      redirect_to @incidence, notice: 'Incidence was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @incidence.destroy
    redirect_to incidences_url, notice: "Incidence was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_incidence
    @incidence = Incidence.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def incidence_params
    params.require(:incidence).permit(:covid_test_id, :user_id, :begin)
  end

  def incidence_params_update
    params.require(:incidence).permit(:delivery, :result)
  end

  def set_variables
    @tests = CovidTest.all.map { |test| [test.name, test.id] }
    @symptoms = Symptom.all
    @places = Place.all
  end

  def set_variables_with_params
    @incidence.set_symptoms(params[:symp]) if params[:symp]
    @incidence.set_places(params[:places]) if params[:places]
  end

  def set_user_symptoms
    @user_symptoms = []
    @user_places = []
  end
end

alerta-covid/app/views/incidences/_form.html.erb
<%= form_with(model: incidence) do |form| %>
  <% if incidence.errors.any? %>
    <div id="error_explanation" class="errors">
      <h2 class="error-title"><%= pluralize(incidence.errors.count, "error") %> prohibited this incidence from being saved:</h2>

      <ul>
        <% incidence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container-incidence">
    <div class="list-symptoms">
      <h3 class="title">Do you have Symptom</h3>
      <% @symptoms.each do |s| %>
        <label class="symptom" for= <%= s.id%> >
          <%= check_box_tag 'symp[]', s.id, @user_symptoms.include?(s.id), id: s.id, class: "input-checkbox"%>
          <label for= <%= s.id%>><%=s.name%></label>
        </label>        
      <% end %>
    </div>
    <div class="covid-test">
      <h3 class="title">About covid test</h3>
      <div class="wrapper">
        <div class="form-group row mt-4">
          <%= form.label :covid_test, class: "col-sm-4 col-form-label"%>
          <div class="col-sm-8">
            <%= select(:incidence, :covid_test_id, @tests, {} ,{class: 'form-control'}) %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= form.label :begin_covid_test, class: "col-4 col-form-label" %>
          <div class="col-8">
            <%= form.date_field :begin, class: incidence.errors.include?(:begin) ? "form-control is-invalid" : "form-control", id:"covid-test"%>
          </div>
        </div>
      </div>
      <div>
        <%= image_tag("Sanitizing.png", class: "image-incidence") %>
      </div>
    </div>
  </div>
  <div class="create-incidence">
      <%= form.submit do%>
        <i class="fas fa-arrow-circle-left"></i>
      <% end %>
  </div>
<% end %>

alerta-covid/app/views/incidences/_form_update.html.erb
<%= form_with(model: incidence) do |form| %>
  <% if incidence.errors.any? %>
    <div id="error_explanation" class="errors">
      <h2><%= pluralize(incidence.errors.count, "error") %> prohibited this incidence from being saved:</h2>

      <ul>
        <% incidence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container-incidence">
    <div class="list-symptoms">
      <h3 class="title">Do you have Symptom</h3>
      <% @symptoms.each do |s| %>
        <label class="symptom" for=<%= s.id %>>
          <%= check_box_tag 'symp[]', s.id, @user_symptoms.include?(s.id), disabled: true%>
          <label for=<%= s.id%>> <%=s.name%> </label>
        </label>     
      <% end %>
    </div>
    <div class="covid-test">
      <h3 class="title"> About covid test</h3>
      <div class="wrapper">
        <div class="from-group row mt-4">
          <%= form.label :covid_test, class: "col-sm-4 col-form-label" %>
          <div class="col-sm-8">
            <%= select(:incidence, :covid_test_id, @tests, {}, {class: "form-control" , disabled: true} ) %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= form.label :begin_covid_test, class: "col-4 col-form-label"%>
          <div class="col-8">
            <%= form.date_field :begin, { class: "form-control" , disabled: true}%>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= form.label :delivery_covid_test, class: "col-4 col-form-label"%>
          <div class="col-8">
            <%= form.date_field :delivery, class: incidence.errors.include?(:delivery) ? "form-control is-invalid" : "form-control" %>
          </div>
        </div>

        <div class="form-group row mt-4">
          <%= form.label :result_covid_test, class: "col-4 col-form-label"%>
          <div class="col-8">
            <%= form.select(:result,[[true,true],[false, false]],{},{ class: "form-control", id: "select"})%>
          </div>
        </div>
        <div>
          <%= image_tag("Sanitizing.png", class: "image-incidence") %>
        </div>
      </div>
    </div>
    <div id="places" class="places">
      <h3 class="title">Add all the places visited in the last 10 days</h3>
      <div class="list-items">
        <% @places.each do |s| %>
          <% if s.area.institution_id == @current_institution.id || current_user.super_admin? %>
            <label for=<%= s.id%> class="card place-item">
              <%= image_tag("Sanitizing.png", class: "image-place")%>
              <span><%=s.name%></span>
              <%= check_box_tag 'places[]', s.id, @user_places.include?(s.id),{array: true, class: "check_box", enabled: true, id: s.id}%>
            </label>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="create-incidence">
    <%= form.submit do%>
    <% end %>
  </div>

<% end %> 

alerta-covid/app/views/incidences/edit.html.erb
<div class="container-fluid">
  <h1 class="title">Editing Incidence</h1>
  <div class="card shadow p-5">
    <%= render 'form_update', incidence: @incidence %>
  </div>
</div>
<div class="container-fluid">
  <%= link_to :back, { class: "btn return-button mt-5 mb-5"} do %>
    <i class="fas fa-arrow-circle-left"></i>
    Back
  <% end %>
  <%= link_to 'show', @incidence, class: "btn btn-success" %>
</div>
<%= javascript_pack_tag 'incidence/edit' %>

alerta-covid/app/views/incidences/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1 class="title">My Incidences</h1>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>User</th>
          <th>Institution</th>
          <th>Type test</th>
          <th>Open</th>
          <th>Close</th>
          <th>Result</th>
          <th>Symptom</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @incidences.each do |incidence| %>
          <tr>
            <td><%= incidence.user.full_name + " " + incidence.user.lastname%></td>
            <td><%= incidence.user.departament.institution.name%></td>
            <td><%= incidence.covid_test.name%></td>
            <td><%= time_ago_in_words(incidence.open)%></td>
            <td><%= incidence.close ? time_ago_in_words(incidence.close) : "Pending"%></td>
            <td><%= !incidence.result.nil? ? incidence.result : "Pending"%></td>
            <td><%= incidence.has_symptoms%></td>
            <td><%= link_to 'Show', incidence, class: "btn btn-success" %></td>
            <td><%= link_to 'Update Result', edit_incidence_path(incidence), class: "btn btn-warning" %></td>
            <td><%= button_to 'Destroy', incidence, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="mt-2 mb-3 col-xs-12">
    <%= will_paginate(@incidences, :renderer => WillPaginate::ActionView::LinkRenderer, class: 'pagination-sm justify-content-center') %>
  </div>

  <div class="mt-2 col-xs-12">
    <%= link_to 'New Incidence', new_incidence_path, class: "new-button" %>
  </div> 
</div>

alerta-covid/app/views/incidences/new.html.erb
<div class="container-fluid">
  <h1 class="title">New Incidence</h1>
  <div class="card shadow p-5">
    <%= render 'form', incidence: @incidence %>
  </div>
</div>
<div class="container-fluid">
  <%= link_to :back, { class: "btn return-button mt-5 mb-5"} do %>
    <i class="fas fa-arrow-circle-left"></i>
    Back
  <% end %>
</div>

alerta-covid/app/views/incidences/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="container-incidence">
    <div class="list-symptoms">
      <h3 class="title">My symptoms</h3>
      <% @incidence.symptoms.each do |s| %>
        <label class="symptom" %> >
          <label><%=s.name%></label>
        </label>
      <% end %>
    </div>
    <div class="covid-test">
      <h3 class="title">About covid test</h3>
      <div class="wrapper">
        <div class="from-group row mt-4">
          <label class="col-sm-4 col-form-label"> Covid Test</label>
          <div class="col-sm-8">
            <label class="form-control"><%= @incidence.covid_test.name%></label>
          </div>
        </div>
        <div class="from-group row mt-4">
          <label class="col-sm-4 col-form-label"> Begin Covid Test</label>
          <div class="col-sm-8">
            <label class="form-control"><%= @incidence.begin%></label>
          </div>
        </div>
        <div class="from-group row mt-4">
          <label class="col-sm-4 col-form-label"> Delivery Covid Test</label>
          <div class="col-sm-8">
            <label class="form-control"><%= @incidence.delivery%></label>
          </div>
        </div>
        <div class="from-group row mt-4">
          <label class="col-sm-4 col-form-label"> Result Covid Test</label>
          <div class="col-sm-8">
            <label class="form-control"><%= @incidence.result%></label>
          </div>
        </div>
      </div>
    </div>
      <div id="places" class="places">
      <h3 class="title">places visited</h3>
      <div class="list-items">
        <% @incidence.places.each do |s| %>
          <label for=<%= s.id%> class="card place-item">
            <%= image_tag("Sanitizing.png", class: "image-place")%>
            <span><%=s.name%></span>
          </label>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <%= link_to :back, { class: "btn return-button mt-5 mb-5"} do %>
    <i class="fas fa-arrow-circle-left"></i>
    Back
  <% end %>
  <%= link_to 'Edit', edit_incidence_path(@incidence), class: "btn btn-warning" %>
</div>