alerta-covid/config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }
  namespace :api do
    namespace :v1 do
      resources :areas, only: [:index]
      resources :covid_tests, only: [:index]
      resources :departaments, only: [:index]
      resources :incidences, only: [:index, :create, :update]
      resources :institutions, only: [:index]
      resources :places, only: [:index]
      resources :symptoms, only: [:index]   
      
      # User confirmation by API
      get 'confirm_user', to: 'confirmations#confirm_user'
      # User Edition by API
      patch :user, to: 'users#update'
      patch 'user_update_password', to: 'users#update_password'
      #User login by API
      post 'login', to: 'sessions#create'
      get '/auto_login', to: 'sessions#auto_login'

      get 'reports/places'
      get 'reports/users'
    end
  end
  
  resources :areas
  resources :covid_tests
  resources :departaments
  resources :incidences
  resources :institutions
  resources :places
  resources :roles
  resources :symptoms  
  
  scope :admin do
    resources :users
  end
  
  root 'home#home'
  get 'home/home'
  get 'home/comfirmation'
  get 'reports/places'
  get 'reports/users'
  # Ex:- scope :active, -> {where(:active => true)}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alerta-covid/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user.role.permissions.each do |permission|
      if permission.subject_class == 'all'
        can permission.action.to_sym, permission.subject_class.to_sym
      else
        can permission.action.to_sym, permission.subject_class.constantize
      end
    end
    if user.has_role? 'Data Reporter'
      can :users, ReportsController
      can :places, ReportsController
    end
  end
end

alerta-covid/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alerta-covid/app/models/area.rb
class Area < ApplicationRecord
  belongs_to :institution
  validates :institution, :name, presence: true
end

alerta-covid/app/models/covid_test.rb
class CovidTest < ApplicationRecord
  validates :name, presence: true
  has_many  :incidences
end

alerta-covid/app/models/departament.rb
class Departament < ApplicationRecord
  validates :name, presence: true
  validates :institution, presence: true
  belongs_to :institution
  has_many :users
end

alerta-covid/app/models/incidence.rb
class Incidence < ApplicationRecord
  validates :user_id, presence: true
  validates :covid_test_id, presence: true
  validates :open, presence: true
  validates :begin, presence: true

  belongs_to :user
  belongs_to :covid_test
  has_many :incidence_symptoms
  has_many :symptoms, through: :incidence_symptoms
  has_many :incidence_places
  has_many :places, through: :incidence_places

  before_update :set_close

  def set_symptoms(symptoms)
    self.symptoms = []
    symptoms.each do |id|
      symp = Symptom.find(id)
      self.symptoms << symp
    end
  end

  def set_places(places)
    self.places = []
    places.each do |id|
      place = Place.find(id)
      self.places << place
    end
  end

  def set_close
    self.close = DateTime.now if close.nil? && !delivery.nil?
  end

  def has_symptoms
    self.symptoms.count > 0 ? "Yes" : "No"
  end

  def has_symptoms?
    self.symptoms.count > 0
  end
end

alerta-covid/app/models/incidence_place.rb
class IncidencePlace < ApplicationRecord
  belongs_to :incidence
  belongs_to :place
end

alerta-covid/app/models/incidence_symptom.rb
class IncidenceSymptom < ApplicationRecord
  belongs_to :incidence
  belongs_to :symptom
end

alerta-covid/app/models/institution.rb
class Institution < ApplicationRecord
    validates :name, presence: true
end

alerta-covid/app/models/permission.rb
class Permission < ApplicationRecord
end

alerta-covid/app/models/place.rb
class Place < ApplicationRecord
  belongs_to :area
  validates :name, :area, presence: true

  has_many :incidence_places
  has_many :incidences, through: :incidence_places


  after_create :generate_qr_code
  after_destroy :destroy_qr_code

  def generate_qr_code
    qr_code = RQRCode::QRCode.new(self.id.to_s)
    png = qr_code.as_png(
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: 'black',
      file: nil,
      fill: 'white',
      module_px_size: 6,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 120
    )
    IO.binwrite("app/assets/images/qr_codes/qrcode_#{self.id.to_s}.png", png.to_s)
  end
  
  def destroy_qr_code
    File.delete("app/assets/images/qr_codes/qrcode_#{self.id.to_s}.png")
  end

  def are_there_active_cases?
    active_cases_teen_days_ago > 0
  end

  def active_cases_teen_days_ago
    self.incidences.where(result: true, delivery: 10.days.ago..Date.today).count
  end
end

alerta-covid/app/models/report.rb
class Report < ApplicationRecord

  def self.to_csv
    CSV.generate do |csv_file|
      csv_file << column_names
        all.each do |report|
          csv_file << report.to_csv
        end
      end
    end
end

alerta-covid/app/models/role.rb
class Role < ApplicationRecord
    validates :name, presence: true
    has_many :users
    has_and_belongs_to_many :permissions
    after_destroy :delete_permissions_role

    def set_permissions(permissions)
        permissions.each do |id|
            permission = Permission.find(id)
            self.permissions << permission
        end
    end

    def delete_permissions_role
      ActiveRecord::Base.connection.execute("DELETE FROM permissions_roles WHERE role_id = #{self.id.to_s}")
    end
end

alerta-covid/app/models/symptom.rb
class Symptom < ApplicationRecord
  has_many :incidence_symptoms
  has_many :incidents, through: :incidence_symptoms
end

alerta-covid/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :role
  belongs_to :departament
  has_many :incidence

  def super_admin?
    self.role.name == "Super Admin"
  end

  def admin_institution?
    self.role.name == "Admin Institution"
  end

  def final_user?
    self.role.name == "Final User"
  end

  def is_signed_in?
    true if user_signed_in?
  end

  def has_role?(role_name)
    Role.all.any? {|role| role.name == role_name}
  end

  def is_admin?
    has_role?("Super Admin")
  end
  
end

alerta-covid/app/helpers/areas_helper.rb
module AreasHelper
end

alerta-covid/app/helpers/home_helper.rb
module HomeHelper
end

alerta-covid/app/helpers/places_helper.rb
module PlacesHelper
end

alerta-covid/app/helpers/roles_helper.rb
module RolesHelper
end

alerta-covid/app/helpers/users_helper.rb
module UsersHelper
end

alerta-covid/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-Light">
    <a class="navbar-brand" href="/">ALERTA COVID</a>

        <ul class="navbar-nav m-auto">
            <li class="nav-item">
                <span class="nav-link" id="currentTime">loading</span> 
            </li>
            <li class="nav-item">
                <span class="nav-link" id="currentDate"></span>
            </li>
        </ul>
         <ul class="navbar-nav mr-md-1">
            <li class="nav-item">
                <%= current_user&.email %>
            </li>
        </ul>
</nav>
<div style="display: none">
    <input type="hidden" readonly="true" value="<%= controller.controller_name %>" id="controller_name">
</div>
<%= javascript_pack_tag 'layouts/navbar' %>

alerta-covid/app/views/layouts/_sidebar.html.erb
<aside class="sidebar" id="sidebar">
	<div class="wrapper">
		<div class="side-item-home" id="side-item-home">
			<i class="fas fa-home"></i>
			<span>HOME</span>
		</div> 
		<% if (can? :index, Institution) %>
			<a class="side-item" id="side-item" href="/institutions">
				<i class="fas fa-building"></i>
				<span>Institutions</span>
			</a>
		<% end %>
		<% if (can? :index, Role) %>
			<a class="side-item" id="side-item" href="/roles">
				<i class="fas fa-user-tag"></i>
				<span>Roles</span>
			</a>
		<% end %>
		<% if (can? :index, User) %>
			<a class="side-item" id="side-item" href=<%= users_path %>>
				<i class="fas fa-users"></i>
				<span>Users</span>
			</a>	
		<% end %>	
		<% if (can? :index, Departament) %>
			<a class="side-item" id="side-item" href="/departaments">
				<i class="fas fa-users-cog"></i>
				<span>Departments</span>
			</a> 
		<% end %>
		<% if (can? :index, Area) %>
			<a class="side-item" id="side-item" href="/areas">
				<i class="fas fa-warehouse"></i>
				<span>Areas</span>
			</a>
		<% end %>
		<% if (can? :index, Place) %>
			<a class="side-item" id="side-item" href="/places">
				<i class="fas fa-map-marker-alt"></i>
				<span>Places</span>
			</a> 	
		<% end %>	 
		<% if (can? :index, Incidence) %>
			<a class="side-item" id="side-item" href="/incidences">
				<i class="fas fa-exclamation-circle"></i>
				<span>My Incidences</span>
			</a>
		<% end %>
		<% if can?(:users, ReportsController) && can?(:places, ReportsController) && !current_user.final_user? %>
			<div class="dropdown">
				<button class="btn dropdown-toggle btn-reports side-item" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<i class="fas fa-tasks"></i>
					<span>Reports</span>	 
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					<a class="dropdown-item" href=<%=reports_users_path%>>Reports by users</a>
					<a class="dropdown-item" href=<%= reports_places_path%>>Reports by places</a>
				</div>
			</div>
		<% end %>
	</div>
	<div class="wrapper">
		<a class="side-item icon" id="side-item" href=<%= edit_registration_path(current_user) %>>
			<i class="fas fa-edit"></i>
			<span>Edit Profile</span>
		</a> 
		<%= link_to destroy_session_path(current_user), class: "side-item icon", method: :delete do%>
			<i class="fas fa-sign-out-alt"></i>
			<span>Logout</span>
		<%end%>
	</div>
</aside>

<%= javascript_pack_tag 'layouts/sidebar' %>

alerta-covid/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlertaCovid</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main-wrapper">
    <% if user_signed_in? %>
      <%= render "layouts/sidebar"%>
    <%end%>
    <main class="content">
      <% if user_signed_in? %>
        <%= render "layouts/navbar" %>
      <% end %>
      <%= yield %>
    </main>
  </body>
  <%= flash_msg.html_safe if flash.any? %>
  <% flash.discard(flash_msg) %>
</html>

alerta-covid/app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= wicked_pdf_stylesheet_link_tag 'pdf'%>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <meta charset="utf-8">
</head>
<body>
  <%= yield %>
</body>
</html>