alerta-covid/config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords',
                                    confirmations: 'users/confirmations' }
  namespace :api do
    namespace :v1 do
      resources :areas, only: [:index]
      resources :covid_tests, only: [:index]
      resources :departaments, only: [:index]
      resources :incidences, only: [:index, :create, :update]
      resources :institutions, only: [:index]
      resources :places, only: [:index]
      resources :symptoms, only: [:index]   
      
      # User confirmation by API
      get 'confirm_user', to: 'confirmations#confirm_user'
      # User Edition by API
      patch :user, to: 'users#update'
      patch 'user_update_password', to: 'users#update_password'
      #User login by API
      post 'login', to: 'sessions#create'
      get '/auto_login', to: 'sessions#auto_login'

      get 'reports/places'
      get 'reports/users'
    end
  end
  
  resources :areas
  resources :covid_tests
  resources :departaments
  resources :incidences
  resources :institutions
  resources :places
  resources :roles
  resources :symptoms  
  
  scope :admin do
    resources :users
  end
  
  root 'home#home'
  get 'home/home'
  get 'home/comfirmation'
  get 'reports/places'
  get 'reports/users'
  # Ex:- scope :active, -> {where(:active => true)}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

alerta-covid/app/models/institution.rb
class Institution < ApplicationRecord
    validates :name, presence: true
end

alerta-covid/app/controllers/api/v1/institutions_controller.rb
class Api::V1::InstitutionsController < Api::V1::ApiController
  
    # GET api/v1/institutions
    def index
      @institutions = Institution.all
      render json: @institutions, status: :ok
    end
  end
  

alerta-covid/app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: %i[ show edit update destroy ]
  
  load_and_authorize_resource
  before_action :load_permissions

  # GET /institutions or /institutions.json
  def index
    if(current_user.super_admin?)
      @institutions = Institution.all.paginate(page: params[:page], per_page: 15)
    else
      @institutions = Institution.all.where(id: current_institution.id).paginate(page: params[:page], per_page: 15)
    end
  end

  # GET /institutions/1 or /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions or /institutions.json
  def create
    if(current_user.super_admin?)
      @institution = Institution.new(institution_params)
      if @institution.save
        redirect_to @institution, notice: "Institution was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /institutions/1 or /institutions/1.json
  def update
    if(current_user.super_admin?)
      if @institution.update(institution_params)
        redirect_to @institution, notice: "Institution was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /institutions/1 or /institutions/1.json
  def destroy
    if(current_user.super_admin?)
      @institution.destroy
      redirect_to institutions_url, notice: "Institution was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def institution_params
      params.require(:institution).permit(:name)
    end
end

alerta-covid/app/views/institutions/_form.html.erb
<%= form_with(model: institution) do |form| %>
  <% if institution.errors.any? %>
    <div id="error_explanation" class="errors">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
        <% institution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card p-5">
    <div class="form-group row">
      <%= form.label :name, class: "form-control-label col-lg-2 col-sm-12" %>
      <div class="col-lg-10 col-sm-12">
        <%= form.text_field :name, class: institution.errors.include?(:name) ? "form-control is-invalid" : "form-control" %>
      </div>
    </div>

    <div class="d-flex flex-column ">
      <%= form.submit class: "btn btn-info" %>
    </div>
  </div>
<% end %>

alerta-covid/app/views/institutions/edit.html.erb
<div class="container container-form d-flex  flex-column ">
  <h1 class="title">Editing Institution</h1>

  <%if(current_user.super_admin?)%>
    <%= render 'form', institution: @institution %>
  <%else%>
    <h2>You're not authorized to edit this template</h2>
  <%end%>

</div>
<div class="container">
  <%= link_to :back, { class: "btn return-button" } do %>
    <i class="fas fa-arrow-circle-left"></i>
    Back
  <% end %>
  <%= link_to 'Show', @institution, class: "btn btn-warning" %>
</div>

alerta-covid/app/views/institutions/index.html.erb
<div class="container container-form ">
  <h1 class="title">Institutions</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @institutions.each do |institution| %>
        <tr>
          <td><%= institution.name %></td>
          <td><%= link_to 'Show', institution, class: "btn btn-success" %></td>
          <%if current_user.super_admin?%>
            <td><%= link_to 'Edit', edit_institution_path(institution), class: "btn btn-warning" %></td>
            <td><%= button_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-2 mb-3 col-xs-12">
    <%= will_paginate(@institutions, :renderer => WillPaginate::ActionView::LinkRenderer, class: 'pagination-sm justify-content-center') %>
  </div>
  <%if current_user.super_admin?%>
    <div class="container">
      <div class="mt-2 col-xs-12">
        <%= link_to 'New Institution', new_institution_path, class: "new-button" %>
      </div>
    </div>
  <%end%>
</div>

alerta-covid/app/views/institutions/new.html.erb
<div class="container container-form">
  <h1 class="title">New Institution</h1>

  <%= render 'form', institution: @institution %>

</div>
<div class="container">
  <%= link_to :back, { class: "btn return-button" } do %>
     <i class="fas fa-arrow-circle-left"></i>
     Back
  <% end %>
</div>

alerta-covid/app/views/institutions/show.html.erb
<div class="container container-form">
  <p id="notice"><%= notice %></p>

  <h1 class="title">Institution Details</h1>
  <div class="card p-5">
      <strong>Name:</strong>
      <%= @institution.name %>
  </div>
</div>

<div class="container">
  <%= link_to :back, { class: "btn return-button" } do %>
    <i class="fas fa-arrow-circle-left"></i>
    Back
  <% end %>
  <%= link_to 'Edit', edit_institution_path(@institution), class: "btn btn-warning" %>
</div>